# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/psialt/repos/meeting-minutes/mybicycle

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/psialt/repos/meeting-minutes/mybicycle

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/psialt/repos/meeting-minutes/mybicycle/CMakeFiles /Users/psialt/repos/meeting-minutes/mybicycle//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/psialt/repos/meeting-minutes/mybicycle/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WhisperQtApp

# Build rule for target.
WhisperQtApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WhisperQtApp
.PHONY : WhisperQtApp

# fast build rule for target.
WhisperQtApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperQtApp.dir/build.make CMakeFiles/WhisperQtApp.dir/build
.PHONY : WhisperQtApp/fast

#=============================================================================
# Target rules for targets named WhisperQtApp_autogen_timestamp_deps

# Build rule for target.
WhisperQtApp_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WhisperQtApp_autogen_timestamp_deps
.PHONY : WhisperQtApp_autogen_timestamp_deps

# fast build rule for target.
WhisperQtApp_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperQtApp_autogen_timestamp_deps.dir/build.make CMakeFiles/WhisperQtApp_autogen_timestamp_deps.dir/build
.PHONY : WhisperQtApp_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named WhisperQtApp_autogen

# Build rule for target.
WhisperQtApp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WhisperQtApp_autogen
.PHONY : WhisperQtApp_autogen

# fast build rule for target.
WhisperQtApp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperQtApp_autogen.dir/build.make CMakeFiles/WhisperQtApp_autogen.dir/build
.PHONY : WhisperQtApp_autogen/fast

#=============================================================================
# Target rules for targets named ggml-base

# Build rule for target.
ggml-base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-base
.PHONY : ggml-base

# fast build rule for target.
ggml-base/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/ggml/src/CMakeFiles/ggml-base.dir/build.make whisper_build/ggml/src/CMakeFiles/ggml-base.dir/build
.PHONY : ggml-base/fast

#=============================================================================
# Target rules for targets named ggml

# Build rule for target.
ggml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml
.PHONY : ggml

# fast build rule for target.
ggml/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/ggml/src/CMakeFiles/ggml.dir/build.make whisper_build/ggml/src/CMakeFiles/ggml.dir/build
.PHONY : ggml/fast

#=============================================================================
# Target rules for targets named ggml-cpu

# Build rule for target.
ggml-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-cpu
.PHONY : ggml-cpu

# fast build rule for target.
ggml-cpu/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/ggml/src/CMakeFiles/ggml-cpu.dir/build.make whisper_build/ggml/src/CMakeFiles/ggml-cpu.dir/build
.PHONY : ggml-cpu/fast

#=============================================================================
# Target rules for targets named ggml-base_autogen_timestamp_deps

# Build rule for target.
ggml-base_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-base_autogen_timestamp_deps
.PHONY : ggml-base_autogen_timestamp_deps

# fast build rule for target.
ggml-base_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/ggml/src/CMakeFiles/ggml-base_autogen_timestamp_deps.dir/build.make whisper_build/ggml/src/CMakeFiles/ggml-base_autogen_timestamp_deps.dir/build
.PHONY : ggml-base_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ggml-base_autogen

# Build rule for target.
ggml-base_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-base_autogen
.PHONY : ggml-base_autogen

# fast build rule for target.
ggml-base_autogen/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/ggml/src/CMakeFiles/ggml-base_autogen.dir/build.make whisper_build/ggml/src/CMakeFiles/ggml-base_autogen.dir/build
.PHONY : ggml-base_autogen/fast

#=============================================================================
# Target rules for targets named ggml_autogen_timestamp_deps

# Build rule for target.
ggml_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml_autogen_timestamp_deps
.PHONY : ggml_autogen_timestamp_deps

# fast build rule for target.
ggml_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/ggml/src/CMakeFiles/ggml_autogen_timestamp_deps.dir/build.make whisper_build/ggml/src/CMakeFiles/ggml_autogen_timestamp_deps.dir/build
.PHONY : ggml_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ggml_autogen

# Build rule for target.
ggml_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml_autogen
.PHONY : ggml_autogen

# fast build rule for target.
ggml_autogen/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/ggml/src/CMakeFiles/ggml_autogen.dir/build.make whisper_build/ggml/src/CMakeFiles/ggml_autogen.dir/build
.PHONY : ggml_autogen/fast

#=============================================================================
# Target rules for targets named ggml-cpu_autogen_timestamp_deps

# Build rule for target.
ggml-cpu_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-cpu_autogen_timestamp_deps
.PHONY : ggml-cpu_autogen_timestamp_deps

# fast build rule for target.
ggml-cpu_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/ggml/src/CMakeFiles/ggml-cpu_autogen_timestamp_deps.dir/build.make whisper_build/ggml/src/CMakeFiles/ggml-cpu_autogen_timestamp_deps.dir/build
.PHONY : ggml-cpu_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ggml-cpu_autogen

# Build rule for target.
ggml-cpu_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-cpu_autogen
.PHONY : ggml-cpu_autogen

# fast build rule for target.
ggml-cpu_autogen/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/ggml/src/CMakeFiles/ggml-cpu_autogen.dir/build.make whisper_build/ggml/src/CMakeFiles/ggml-cpu_autogen.dir/build
.PHONY : ggml-cpu_autogen/fast

#=============================================================================
# Target rules for targets named ggml-blas

# Build rule for target.
ggml-blas: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-blas
.PHONY : ggml-blas

# fast build rule for target.
ggml-blas/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/ggml/src/ggml-blas/CMakeFiles/ggml-blas.dir/build.make whisper_build/ggml/src/ggml-blas/CMakeFiles/ggml-blas.dir/build
.PHONY : ggml-blas/fast

#=============================================================================
# Target rules for targets named ggml-blas_autogen_timestamp_deps

# Build rule for target.
ggml-blas_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-blas_autogen_timestamp_deps
.PHONY : ggml-blas_autogen_timestamp_deps

# fast build rule for target.
ggml-blas_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/ggml/src/ggml-blas/CMakeFiles/ggml-blas_autogen_timestamp_deps.dir/build.make whisper_build/ggml/src/ggml-blas/CMakeFiles/ggml-blas_autogen_timestamp_deps.dir/build
.PHONY : ggml-blas_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ggml-blas_autogen

# Build rule for target.
ggml-blas_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-blas_autogen
.PHONY : ggml-blas_autogen

# fast build rule for target.
ggml-blas_autogen/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/ggml/src/ggml-blas/CMakeFiles/ggml-blas_autogen.dir/build.make whisper_build/ggml/src/ggml-blas/CMakeFiles/ggml-blas_autogen.dir/build
.PHONY : ggml-blas_autogen/fast

#=============================================================================
# Target rules for targets named ggml-metal

# Build rule for target.
ggml-metal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-metal
.PHONY : ggml-metal

# fast build rule for target.
ggml-metal/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/ggml/src/ggml-metal/CMakeFiles/ggml-metal.dir/build.make whisper_build/ggml/src/ggml-metal/CMakeFiles/ggml-metal.dir/build
.PHONY : ggml-metal/fast

#=============================================================================
# Target rules for targets named ggml-metal_autogen_timestamp_deps

# Build rule for target.
ggml-metal_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-metal_autogen_timestamp_deps
.PHONY : ggml-metal_autogen_timestamp_deps

# fast build rule for target.
ggml-metal_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/ggml/src/ggml-metal/CMakeFiles/ggml-metal_autogen_timestamp_deps.dir/build.make whisper_build/ggml/src/ggml-metal/CMakeFiles/ggml-metal_autogen_timestamp_deps.dir/build
.PHONY : ggml-metal_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ggml-metal_autogen

# Build rule for target.
ggml-metal_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-metal_autogen
.PHONY : ggml-metal_autogen

# fast build rule for target.
ggml-metal_autogen/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/ggml/src/ggml-metal/CMakeFiles/ggml-metal_autogen.dir/build.make whisper_build/ggml/src/ggml-metal/CMakeFiles/ggml-metal_autogen.dir/build
.PHONY : ggml-metal_autogen/fast

#=============================================================================
# Target rules for targets named whisper

# Build rule for target.
whisper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 whisper
.PHONY : whisper

# fast build rule for target.
whisper/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/src/CMakeFiles/whisper.dir/build.make whisper_build/src/CMakeFiles/whisper.dir/build
.PHONY : whisper/fast

#=============================================================================
# Target rules for targets named whisper_autogen_timestamp_deps

# Build rule for target.
whisper_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 whisper_autogen_timestamp_deps
.PHONY : whisper_autogen_timestamp_deps

# fast build rule for target.
whisper_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/src/CMakeFiles/whisper_autogen_timestamp_deps.dir/build.make whisper_build/src/CMakeFiles/whisper_autogen_timestamp_deps.dir/build
.PHONY : whisper_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named whisper_autogen

# Build rule for target.
whisper_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 whisper_autogen
.PHONY : whisper_autogen

# fast build rule for target.
whisper_autogen/fast:
	$(MAKE) $(MAKESILENT) -f whisper_build/src/CMakeFiles/whisper_autogen.dir/build.make whisper_build/src/CMakeFiles/whisper_autogen.dir/build
.PHONY : whisper_autogen/fast

WhisperQtApp_autogen/mocs_compilation.o: WhisperQtApp_autogen/mocs_compilation.cpp.o
.PHONY : WhisperQtApp_autogen/mocs_compilation.o

# target to build an object file
WhisperQtApp_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperQtApp.dir/build.make CMakeFiles/WhisperQtApp.dir/WhisperQtApp_autogen/mocs_compilation.cpp.o
.PHONY : WhisperQtApp_autogen/mocs_compilation.cpp.o

WhisperQtApp_autogen/mocs_compilation.i: WhisperQtApp_autogen/mocs_compilation.cpp.i
.PHONY : WhisperQtApp_autogen/mocs_compilation.i

# target to preprocess a source file
WhisperQtApp_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperQtApp.dir/build.make CMakeFiles/WhisperQtApp.dir/WhisperQtApp_autogen/mocs_compilation.cpp.i
.PHONY : WhisperQtApp_autogen/mocs_compilation.cpp.i

WhisperQtApp_autogen/mocs_compilation.s: WhisperQtApp_autogen/mocs_compilation.cpp.s
.PHONY : WhisperQtApp_autogen/mocs_compilation.s

# target to generate assembly for a file
WhisperQtApp_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperQtApp.dir/build.make CMakeFiles/WhisperQtApp.dir/WhisperQtApp_autogen/mocs_compilation.cpp.s
.PHONY : WhisperQtApp_autogen/mocs_compilation.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperQtApp.dir/build.make CMakeFiles/WhisperQtApp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperQtApp.dir/build.make CMakeFiles/WhisperQtApp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WhisperQtApp.dir/build.make CMakeFiles/WhisperQtApp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... WhisperQtApp_autogen"
	@echo "... WhisperQtApp_autogen_timestamp_deps"
	@echo "... ggml-base_autogen"
	@echo "... ggml-base_autogen_timestamp_deps"
	@echo "... ggml-blas_autogen"
	@echo "... ggml-blas_autogen_timestamp_deps"
	@echo "... ggml-cpu_autogen"
	@echo "... ggml-cpu_autogen_timestamp_deps"
	@echo "... ggml-metal_autogen"
	@echo "... ggml-metal_autogen_timestamp_deps"
	@echo "... ggml_autogen"
	@echo "... ggml_autogen_timestamp_deps"
	@echo "... whisper_autogen"
	@echo "... whisper_autogen_timestamp_deps"
	@echo "... WhisperQtApp"
	@echo "... ggml"
	@echo "... ggml-base"
	@echo "... ggml-blas"
	@echo "... ggml-cpu"
	@echo "... ggml-metal"
	@echo "... whisper"
	@echo "... WhisperQtApp_autogen/mocs_compilation.o"
	@echo "... WhisperQtApp_autogen/mocs_compilation.i"
	@echo "... WhisperQtApp_autogen/mocs_compilation.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

